"Are people from that moon with the oceans going to tell our dolphins anything bad about us?"
"my TV could be bigger"
"Death"
"Aaron from marketing is a dick"
"Still haven't had a KFC double down"
"This app doesn't have a theme song"
